name: Codespell
on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
          only_warn: 1
          path: |
            Documentation/block/blkfilter.rst, \
            Documentation/block/blksnap.rst, \
            block/blk-core.c \
            block/blk-filter.c, \
            include/linux/blk-filter.h, \
            include/uapi/linux/blk-filter.h, \
            drivers/block/blksnap, \
            include/uapi/linux/blksnap.h